### ISSUE TITLE
Suggestion on tasks 2 and 3

### ISSUE THREAD

**Issue by Felipe-Hub** [ironhack-labs/lab-sql-3#1]
@sandrabosk 

Students were not satisfied with column original_language_id having only null values, no way to check if the query is correct, maybe use another column that has different values in.

**Comment by haggarw3** [comment]
For question 2, instead of original_language_id, I have used language_id now

I have replaced question 3 with a new question. The idea behind the question is similar but on a different column

**Comment by sandrabosk** [comment]
Merged. Solution updated. Thank you both!
